# Generated by Django 4.2.3 on 2023-12-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_question_submission_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='content', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='content', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=50),
        ),
    ]
